$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command

command: >-
  python train.py
  --data ${{inputs.data}}
  --n_estimators 200
  --max_depth 10
  --model_output ${{outputs.model_output}}

environment: azureml:train-env:5

inputs:
  data:
    type: uri_folder
    path: azureml:skycore_test_data:1
    mode: download

outputs:
  model_output:
    type: uri_folder
    mode: rw_mount

compute: azureml:lastprojectcompute
experiment_name: project_III_MLOPS
description: "Training job for SkyCore"
display_name: "SkyCore Training Run"
