name: read-yaml

on:
  workflow_call:
    inputs:
      file_name:
        required: true
        type: string
        default: mlops/azureml/train/config-infra-prod.yml
    outputs:
      resource_group:
        description: "Resource group name"
        value: ${{ jobs.read-yaml.outputs.resource_group }}
      aml_workspace:
        description: "AML workspace name"
        value: ${{ jobs.read-yaml.outputs.aml_workspace }}
    secrets:
      AZURE_CREDENTIALS:
        required: true

permissions:
  contents: read

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      resource_group: ${{ steps.extract.outputs.resource_group }}
      aml_workspace: ${{ steps.extract.outputs.aml_workspace }}
    steps:
      - uses: actions/checkout@v4

      - name: Create credentials file
        run: |
          mkdir -p mlops/config
          cat > mlops/config/azure_credentials.json << 'EOF'
          {
            "AZURE_SUBSCRIPTION_ID": "${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}",
            "RESOURCE_GROUP": "streaming_autovehicle_pricing_MLOPS",
            "WORKSPACE_NAME": "project_III_MLOPS",
            "AZURE_CLIENT_ID": "${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}",
            "AZURE_CLIENT_SECRET": "${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}",
            "AZURE_TENANT_ID": "${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}"
          }
          EOF

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set RG and WS
        run: |
          echo "RESOURCE_GROUP=streaming_autovehicle_pricing_MLOPS" >> $GITHUB_ENV
          echo "WORKSPACE_NAME=project_III_MLOPS" >> $GITHUB_ENV

      - name: Update Azure CLI
        run: |
          sudo az upgrade --yes
          az --version
      
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq
      
      - id: extract
        run: |
          set -euo pipefail
          content=$(cat ${{ inputs.file_name }})
          echo "resource_group=$(echo \"$content\" | yq '.resource_group')" >> $GITHUB_OUTPUT
          echo "aml_workspace=$(echo \"$content\" | yq '.aml_workspace')" >> $GITHUB_OUTPUT
